/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobile_androidtest_JNIUtil */

#ifndef _Included_com_mobile_androidtest_JNIUtil
#define _Included_com_mobile_androidtest_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobile_androidtest_JNIUtil
 * Method:    getNativeStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mobile_androidtest_JNIUtil_getNativeStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
