/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobile_androidtest_SignatureUtil */

#ifndef _Included_com_mobile_androidtest_SignatureUtil
#define _Included_com_mobile_androidtest_SignatureUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobile_androidtest_SignatureUtil
 * Method:    checkSignature
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mobile_androidtest_SignatureUtil_checkSignature
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
